"""empty message

Revision ID: 4caaab3415c6
Revises: 66c568a6cfa7
Create Date: 2019-09-11 11:17:48.205438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4caaab3415c6'
down_revision = '66c568a6cfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('avg_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'avg_rating')
    # ### end Alembic commands ###
