"""empty message

Revision ID: d31bbb5355ae
Revises: 4caaab3415c6
Create Date: 2019-09-18 23:25:26.455166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31bbb5355ae'
down_revision = '4caaab3415c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movieid'], ['movies.movieid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validations_id'), 'validations', ['id'], unique=False)
    op.create_index(op.f('ix_validations_timestamp'), 'validations', ['timestamp'], unique=False)
    op.add_column('movies', sa.Column('N_ratings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'N_ratings')
    op.drop_index(op.f('ix_validations_timestamp'), table_name='validations')
    op.drop_index(op.f('ix_validations_id'), table_name='validations')
    op.drop_table('validations')
    # ### end Alembic commands ###
